- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest
# line 7 defines package module
# line 9 defines what to install
- name: install the latest version of yum-utils
  yum: 
    name: yum-utils
    state: latest
- name: Run a command that adds the HC linux repository
  shell: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  args:
    executable: /bin/bash
- name: install the latest version of Vault
  yum: 
    name: vault
    state: latest
- name: Copy the hcl file to the proper location
  copy:
    src: roles/vault-service/tasks/vault.hcl
    dest: /etc/
- name: restart vault server
  shell: systemctl restart vault
  args:
    executable: /bin/bash
- name: check status
  shell: systemctl status vault
  args:
    executable: /bin/bash