version: 0.2
  
phases:
  build:
    commands:
      - aws cloudformation create-stack --template-url https://hashicorptestingbucket.s3.amazonaws.com/EC2_build/src/main/cft/EC2CFT.yml --stack-name jacob-ec2-test --capabilities CAPABILITY_IAM
               
reports:
  report-group-name-or-arn:
    reports_group:
      files:
        - my-test-report-file.json
artifacts:
  files:
    - '**/*'
  name: EC2BuildSpec-$(date +%Y-%m-%d)
  enable-symlinks: yes
#   s3-prefix: prefix
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       name: secondary-artifact-name
#       discard-paths: no | yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: no | yes
#       base-directory: location

