version: 0.2

        
phases:
  build:
    commands:
      - aws cloudformation create-stack 
          --template-url https://hashicorptestingbucket.s3.amazonaws.com/InfrastructureFoundations-RefArchitecture/src/CFT/ECR_template.yml 
          --stack-name johann-ecr-test
            
reports:
  report-group-name-or-arn:
    reports_group:
      files:
        - my-test-report-file.json
# artifacts:
#   files:
#     - location
#     - location
#   name: artifact-name
#   discard-paths: no | yes
#   base-directory: location
#   exclude-paths: excluded paths
#   enable-symlinks: no | yes
#   s3-prefix: prefix
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       name: secondary-artifact-name
#       discard-paths: no | yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: no | yes
#       base-directory: location

