Parameters:
  Template:
    Description: The template to be deployed. Will also run through Validation
    Type: 
  Subnet:
    Description: Please enter the subnet to be used for this configuration
    Type: AWS::EC2::VPC
    Properties:

  Security-role:
    Description: Please enter the security role
  VPC:
    Description: Please enter the VPC used for the project
  ArtifactStoreParameter:
    Description: The artifact store
 
   Type: AWS::S3::Bucket
    Properties:

  
  
  
  
#artifact store, template url, etc
#this is how we combine the two pipelines into one
#things to look into for paramaterization:
# -custom resources: AWS::CloudFormation::CustomResource, https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html
# -CodeBuild Artifacts: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-artifacts.html
# -Dynamic References: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html
Mappings:

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactStoreParameter
        Type: s3
      RoleArn: arn:aws:iam::396791034774:role/service-role/pipeline-testing
      Stages:
        - Name: Source
          Actions:
              - Name: EC2Source
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Provider: S3
                  Version: 1
                OutputArtifacts:
                - Name: EC2Artifact
                Configuration:
                  S3Bucket: hashicorptestingbucket
                  S3ObjectKey: EC2_build/EC2_build.zip
              - Name: validationSource
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Provider: S3
                  Version: 1
                OutputArtifacts:
                - Name: validationArtifact
                Configuration:
                  S3Bucket: hashicorptestingbucket
                  S3ObjectKey: cft_validation/cft_val.zip
        - Name: Validation
          Actions:
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: 1
            Name: ValidationBuild
            InputArtifacts: 
              - valArtifact
            Configuration:
              ProjectName: cft-validation
        - Name: deployToCatalog
          Actions:
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: ServiceCatalog
              Version: 1
            Name: CatalogDeploy
            InputArtifacts:
              - EC2Artifact
            Configuration:
              TemplateFilePath: /src/main/cft/EC2CFT.yml
              ProductVersionName: Version-1.0
              ProductType: CLOUD_FORMATION_TEMPLATE
              ProductId: prod-46wlga2juncme
