AWSTemplateFormatVersion: '2010-09-09'
###  Creates a pipeline with source, validation and catalog deploy stages

Parameters:
  Environment:
    Description: Which account is the environment being creates
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  SourceBucketName:
    Description: 'S3 BucketName for source code. For example: infrafoundationstest'
    Type: String
    Default: "infrafoundationstest"
  ArtifactBucketName:
    Description: 'S3 BucketName for CodeBuild Artifacts. For example: pipelineartifactsource'
    Type: String
    Default: "pipelineartifactsource"

Resources:
  #Creates the validation testing codebuild project
  SourceBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref SourceBucketName

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Join ['', [PipelineFoundationsCodeBuild, !Ref Environment]]
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::codepipeline-${AWS::Region}-*
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Resource:
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub arn:aws:s3:::${SourceBucketName}
                  - !Sub arn:aws:s3:::${SourceBucketName}/*
                  - !Sub arn:aws:s3:::${ArtifactBucketName}
                  - !Sub arn:aws:s3:::${ArtifactBucketName}/*
              - Effect: Allow
                Action:
                  - s3:List*
                  - s3:Describe*
                  - ssm:PutParameter
                  - ssm:GetParameter
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                Resource: "*"
              - Effect: Allow
                Action:
                  - servicecatalog:ListProvisioningArtifacts
                  - servicecatalog:CreateProvisioningArtifact
                  - servicecatalog:DescribeProvisioningArtifact
                  - servicecatalog:DescribeProductAsAdmin
                  - servicecatalog:DeleteProvisioningArtifact
                  - servicecatalog:UpdateProduct
                  - servicecatalog:CreateProduct
                  - servicecatalog:DeleteProduct
                  - servicecatalog:AssociateProductWithPortfolio
                  - servicecatalog:SearchProductsAsAdmin
                  - servicecatalog:ListServiceActionsForProvisioningArtifact
                Resource: "*"

  ValidationCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: InfraFoundationsValCodeBuild
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: S3
        Path: CFT-Pipeline-test
        Packaging: ZIP
        NamespaceType: BUILD_ID
        Name: ValOutArt.zip
        Location: !Ref ArtifactBucketName
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:5.0
      Source:
        Type: S3
        Location: !Join
          - '/'
          - - !Ref SourceBucket
            - Source.zip
        BuildSpec: src/validation_build/buildspec.yml

  #Creates the deployment to Service Catalog
  CatalogCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: InfraFoundationsCatalogCodeBuild
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: S3
        Path: catalog-test
        Packaging: ZIP
        NamespaceType: BUILD_ID
        Name: catalogtest.zip
        Location: !Ref ArtifactBucketName
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:5.0
        #creates environment variable to be used in the catalog deployment
        EnvironmentVariables:
          - Name: CATALOG_PORTFOLIO
            Type: PLAINTEXT
            Value: !Ref CatalogPortfolio
          - Name: SOURCE_BUCKET_NAME
            Type: PLAINTEXT
            Value: !Ref SourceBucket
      Source:
        Type: S3 
        Location: !Join
          - '/'
          - - !Ref SourceBucket
            - Source.zip
        BuildSpec: src/service_catalog_build/buildspec.yml

  #Creates a Service Catalog Portfolio for products to be stored in
  CatalogPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      Description: Portfolio to host instance products 
      DisplayName: AWS Resources
      ProviderName: Vertical Relevance

  #Creates association of desired users to have access to the products
  EndUsers:
      Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
      Properties:
        PortfolioId: !Ref CatalogPortfolio
        PrincipalARN: !GetAtt EndUsersIAMGroup.Arn
        PrincipalType: IAM

  EndUsersIAMGroup:
    Type: AWS::IAM::Group
