AWSTemplateFormatVersion: '2010-09-09'
###  Creates a pipeline with source, validation and catalog deploy stages

Parameters:
#Describes the environment for the project
  Environment:
    Description: Which account is the environment being creates
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  ArtifactBucketName:
    Description: 'S3 BucketName for CodeBuild Artifacts. For example: pipelineartifactsource'
    Type: String
    Default: "pipelineartifactsource"

Mappings:
  #These mappings allow for simple substitution of various environment parameters
  PipelineDetails:
    SourceStage:
      RepositoryName: TestRepositoryInfraFoundations
      BranchName: automation-refactor
    EC2:
      TemplateSource: ec2Art
      S3CFTZIP: EC2_build/EC2_build.zip
      FileName: /templates/EC2CFT.yml 
    
    ElastiCache:
      TemplateSource: ecrArt
      S3CFTZIP: elasticache_build/ecr_file.zip
      FileName: /templates/ECR_template.yml 
  
    CommonVariables:
      ValProjectName: InfraFoundationsValCodeBuild
      CatalogProjectName: InfraFoundationsCatalogCodeBuild

    ArtifactVariables:
      ValidationBuild: ValOutArt
      ValSource: ValArt

Resources: 
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref ArtifactBucketName

  PipelineFoundationsRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !FindInMap ['PipelineDetails', 'SourceStage', 'RepositoryName']
      RepositoryDescription: The codecommit repository for the Pipeline Foundations pipeline

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /service-role/
      Policies:
        - PolicyName: !Join ['', [PipelineFoundationsCodePipeline, !Ref Environment]]
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Action:
                  - iam:PassRole
                Resource: "*"
                Effect: Allow
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                    - cloudformation.amazonaws.com
              - Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                Resource: "*"
                Effect: Allow
              - Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:GetApplication
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                Resource: "*"
                Effect: Allow
              - Action:
                  - codestar-connections:UseConnection
                Resource: "*"
                Effect: Allow
              - Action:
                  - lambda:InvokeFunction
                  - lambda:ListFunctions
                Resource: "*"
                Effect: Allow
              - Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                Resource: "*"
                Effect: Allow
              - Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuildBatches
                  - codebuild:StartBuildBatch
                Resource: "*"
                Effect: Allow
              - Effect: Allow
                Action:
                  - servicecatalog:ListProvisioningArtifacts
                  - servicecatalog:CreateProvisioningArtifact
                  - servicecatalog:DescribeProvisioningArtifact
                  - servicecatalog:DeleteProvisioningArtifact
                  - servicecatalog:UpdateProduct
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactBucketName}
                  - !Sub arn:aws:s3:::${ArtifactBucketName}/*
              - Effect: Allow
                Action:
                  - s3:List*
                  - s3:Describe*
                Resource:
                  - '*'

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        #Sources the template(s) from CodeCommit
        - Name: Source
          Actions: 
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: !FindInMap ['PipelineDetails', 'SourceStage', 'RepositoryName']
                BranchName: !FindInMap ['PipelineDetails', 'SourceStage', 'BranchName']
              OutputArtifacts:
                - Name: !FindInMap ['PipelineDetails', 'ArtifactVariables', 'ValSource'] 
        #Validates the template(s) and builds the template(s) so long as validation is passed
        - Name: Validation
          Actions:
            #Validation Codebuild
            - Name: ValBuild 
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: !FindInMap ['PipelineDetails', 'ArtifactVariables', 'ValSource'] 
              Configuration:
                ProjectName: !FindInMap ['PipelineDetails', 'CommonVariables', 'ValProjectName']
              OutputArtifacts:
                - Name: !FindInMap ['PipelineDetails', 'ArtifactVariables', 'ValidationBuild']
              RunOrder: 1
            #Catalog deployment
            - Name: CatalogBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: !FindInMap ['PipelineDetails', 'ArtifactVariables', 'ValSource'] 
              Configuration:
                ProjectName: !FindInMap ['PipelineDetails','CommonVariables','CatalogProjectName'] 
              RunOrder: 2


Outputs:
    PipelineRepoName:
        Description: "Pipeline Repo Name"
        Value: !GetAtt PipelineFoundationsRepo.Name



