Parameters:
#Why are they ordered alphabetically when creating the stack regardless of how we place them here?
  VPC:
    Description: Please select the VPC used for the project
    Type: AWS::EC2::VPC::Id
  Subnet:
    Description: Please select the subnet to be used for this configuration
    Type: AWS::EC2::Subnet::Id
  WhichInstance:
    Description: What program will you be installing?
    Type: String
    AllowedValues:
      - ElastiCache
      - EC2
Mappings:
  PipelineDetails:
    EC2:
      TemplateSource: ec2Art
      S3CFTZIP: EC2_build/EC2_build.zip
      FileName: /src/main/cft/EC2CFT.yml 
    ElastiCache:
      TemplateSource: ecrArt
      S3CFTZIP: elasticache_build/ecr_file.zip
      FileName: /src/main/cft/ECR_template.yml 
    CommonVariables:
      Provider: S3
      FileBucket: hashicorptestingbucket
      RoleArn: arn:aws:iam::396791034774:role/service-role/pipeline-testing
      ArtifactBucket: artifacttestingbucket
      ValSource: valArt
      ValZip: cft_validation/cft_val.zip
      ProjectName: cft-validation
      #/src/main/cft/ECR_template.yml  #join str.join(/src/main/cft/, userinput) %Y %m %d
Resources:  
  # ArtifactStoreParameter:
  #   Description: The artifact store
  #   Type: AWS::S3::Bucket
  #   Properties:
  CatalogProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: ecr-test1
      Owner: Vertical Relevance
      ProvisioningArtifactParameters:
        - Name: CreateCatalogProduct
          Info:
            LoadTemplateFromURL: https://hashicorptestingbucket.s3.amazonaws.com/elasticache_build/src/main/cft/ECR_template.yml #make blank file
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: CFT-Pipeline-test
      ArtifactStore:
        Location: !FindInMap ['PipelineDetails', 'CommonVariables', 'ArtifactBucket']
        Type: !FindInMap ['PipelineDetails','CommonVariables', 'Provider']
      RoleArn: !FindInMap ['PipelineDetails', 'CommonVariables','RoleArn']
      Stages:
        - Name: Source
          Actions:
            - Name: instanceSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: !FindInMap ['PipelineDetails','CommonVariables', 'Provider']
                Version: 1
              OutputArtifacts: 
                - Name: !FindInMap ['PipelineDetails', !Ref WhichInstance, 'TemplateSource'] #join str.join(/src/main/cft/, userinput) %Y %m %d 
              Configuration:
                S3Bucket: !FindInMap ['PipelineDetails', 'CommonVariables', 'FileBucket']
                S3ObjectKey: !FindInMap ['PipelineDetails',!Ref WhichInstance, 'S3CFTZIP']
              RunOrder: '1'
            - Name: valSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: !FindInMap ['PipelineDetails','CommonVariables', 'Provider']
                Version: 1
              OutputArtifacts:
                - Name: !FindInMap ['PipelineDetails', 'CommonVariables', 'ValSource']
              Configuration:
                S3Bucket: !FindInMap ['PipelineDetails', 'CommonVariables', 'FileBucket']
                S3ObjectKey: !FindInMap ['PipelineDetails', 'CommonVariables', 'ValZip']
              RunOrder: '2'
        - Name: Validation
          Actions:
            - Name: ValBuild 
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: !FindInMap ['PipelineDetails', 'CommonVariables', 'ValSource']
              Configuration:
                ProjectName: !FindInMap ['PipelineDetails', 'CommonVariables', 'ProjectName']
              RunOrder: '3'
        - Name: Catalog #Why is this completed before validation is completed?
          Actions:
            - Name: CatalogDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ServiceCatalog
                Version: 1
              InputArtifacts:
                - Name: !FindInMap ['PipelineDetails', !Ref WhichInstance, 'TemplateSource']
              Configuration:
                TemplateFilePath: !FindInMap ['PipelineDetails', !Ref WhichInstance, 'FileName']
                ProductVersionName: !Ref WhichInstance
                ProductType: CLOUD_FORMATION_TEMPLATE
                ProductId: !Ref CatalogProduct
              RunOrder: '4'


