Parameters:
  VPC:
    Description: Please select the VPC used for the project
    Type: AWS::EC2::VPC::Id
  Subnet:
    Description: Please select the subnet to be used for this configuration
    Type: AWS::EC2::Subnet::Id
  S3CFTZIP: 
    Description: Give path to zip file of CFT. For Example "cft_validation/cft_val.zip"
    Type: String
    Default: elasticache_build/ecr_file.zip
  TemplateName:
    Description: Please enter the file name inlcuding .yml
    Type: String
#artifact store(its a bucket where people will store their artifacts), should we make it ourselves or allow them to input it?
#


Mappings:
  PipelineDetails:
    CommonVariables:
      provider: S3
      file_bucket: hashicorptestingbucket
      role_arn: arn:aws:iam::396791034774:role/service-role/pipeline-testing
    ArtifactVariables:
      Val_Source: valArt
      Template_Source: ecrArt
      artifact_bucket: artifacttestingbucket
    Validation:
      Val_Zip: cft_validation/cft_val.zip
      Project_Name: cft-validation

Resources:  
  # ArtifactStoreParameter:
  #   Description: The artifact store
  #   Type: AWS::S3::Bucket
  #   Properties:
  CatalogProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: ecr-test1
      Owner: Vertical Relevance
    ProvisioningArtifactParameters:
      ProvisioningArtifactProperties:
        Info:
          LoadTemplateFromURL: "https://hashicorptestingbucket.s3.amazonaws.com/elasticache_build/src/main/cft/ECR_template.yml" #add to map
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: CFT-Pipeline-test
      ArtifactStore:
        Location: !FindInMap ['PipelineDetails', 'ArtifactVariables', 'artifact_bucket']  #artifacttestingbucket 
        Type: !FindInMap ['PipelineDetails','CommonVariables', 'provider']  #S3 
      RoleArn: !FindInMap ['PipelineDetails', 'CommonVariables','role_arn']  #arn:aws:iam::396791034774:role/service-role/pipeline-testing #add to map
      Stages:
        - Name: Source
          Actions:
            - Name: ecrSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: !FindInMap ['PipelineDetails','CommonVariables', 'provider'] #S3 #add to map
                Version: 1
              OutputArtifacts:
                - Name: !FindInMap ['PipelineDetails', 'ArtifactVariables', 'Template_Source'] #ecrArt #add to map
              Configuration:
                S3Bucket: !FindInMap ['PipelineDetails', 'CommonVariables', 'file_bucket'] #hashicorptestingbucket #add to map
                S3ObjectKey: !Ref S3CFTZIP
              RunOrder: '1'
            - Name: valSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: !FindInMap ['PipelineDetails','CommonVariables', 'provider'] #S3 #add to map
                Version: 1
              OutputArtifacts:
                - Name: !FindInMap ['PipelineDetails', 'ArtifactVariables', 'Val_Source'] #valArt #add to map
              Configuration:
                S3Bucket: !FindInMap ['PipelineDetails', 'CommonVariables', 'file_bucket'] #hashicorptestingbucket #add to map
                S3ObjectKey: !FindInMap ['PipelineDetails', 'Validation', 'Val_Zip'] #cft_validation/cft_val.zip  #change to mapping
              RunOrder: '2'
        - Name: Validation
          Actions:
            - Name: ValBuild 
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: !FindInMap ['PipelineDetails', 'ArtifactVariables', 'Val_Source'] #valArt #add to map
              Configuration:
                ProjectName: !FindInMap ['PipelineDetails', 'Validation', 'Project_Name'] #cft-validation #add to map
              RunOrder: '3'
        - Name: Catalog
          Actions:
            - Name: CatalogDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ServiceCatalog
                Version: 1
              InputArtifacts:
                - Name: !FindInMap ['PipelineDetails', 'ArtifactVariables', 'Template_Source'] #ecrArt #add to map
              Configuration:
                TemplateFilePath: /src/main/cft/ECR_template.yml  #join str.join(/src/main/cft/, userinput) %Y %m %d
                ProductVersionName: RedisTest
                ProductType: CLOUD_FORMATION_TEMPLATE
                ProductId: prod-xwootx74f3zzc #!Ref CatalogProduct
              RunOrder: '4'


