version: 0.2
  
phases:
  build:
    commands:
      # Navigates to catalog deployment folder and executes the script
      - cd service_catalog_build/
      - python3 service_catalog.py
          

 