project:
  name: cft-validation
  regions:
    - us-east-1
  # s3_bucket: s3://hashicorpoutputbucket/

tests:
  test_ec2:
    template: ./templates/EC2CFT.yml
    regions:
    - us-east-1
  test_ecr:
    template: ./templates/ECR_template.yml