version: 0.2
phases:
  install:
    runtime-versions:
        ruby: 2.6    
    commands:
    - pip install --upgrade pip
    - pip3 install awscli --upgrade --quiet
    - pip3 install cfn-lint --quiet
    - pip3 install detect-secrets --quiet            
    - pip3 install taskcat --quiet
  build:
    commands:
    - cfn-lint --version
    - taskcat --version
    - detect-secrets --version
    # - echo starting taskcat
    # - taskcat test run 
    # - echo taskcat test successful
    - echo starting cfn-lint
    - cfn-lint -b templates/ECR_template.yml templates/EC2CFT.yml
    - echo cfn-lint successful
    - echo starting detect secrets
    - detect-secrets scan EC2CFT.yml
    - detect-secrets scan ECR_template.yml
    - echo detect secrets successful
