version: 0.2
phases:
  install:
    runtime-versions:
        ruby: 2.6    
    commands:
    - pip install --upgrade pip
    - pip3 install awscli --upgrade --quiet
    - pip3 install cfn-lint --quiet
    - pip3 install detect-secrets --quiet            
    - pip3 install taskcat --quiet
  build:
    commands:
    # - echo starting taskcat
    # - taskcat test run 
    # - echo taskcat test successful
    - cfn-lint -b templates/ECR_template.yml templates/EC2CFT.yml #How do we reference a singular template that was passed in at a different stage? If its through artifacts, how do we ensure its the most recent artifact?
    - detect-secrets scan EC2CFT.yml
    - detect-secrets scan ECR_template.yml

artifacts:
  files: 
    - '**/*'
  name: valArtifact-$(date +%Y-%m-%d)
  enable-symlinks: yes