AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Cloud Formation Template to allow for selection of various sizes of EC2
  instances
Parameters: 
  Environment:
    Description: Which account is the environment being creates
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  SourceBucketName:
      Description: 'S3 BucketName for Python functions. For example: infrafoundationstest'
      Type: String
      Default: "infrafoundationstest"
  VPC:
    Description: Please select the VPC used for the project
    Type: AWS::EC2::VPC::Id
    Default: vpc-0b8ad3ab815f525e8

Mappings: 
  EC2Details:
    #Details shared across environments
    CommonDetails:
      InstanceType: t2.medium
    #Depending on which environment is chosen, different AZ's and subnets are used to help keep the environments separate
    dev:
      AMI: 'ami-0742b4e673072066f'
      AvailabilityZone: us-east-1a
      KeyName: KafkaDevKey
      SubnetId: subnet-0ec1bf2103401e3a5
    prod:
      AMI: 'ami-0742b4e673072066f'
      AvailabilityZone: us-east-1b
      KeyName: KafkaProdKey
      SubnetId: subnet-02cc41ade079189c2
    qa:
      AMI: 'ami-0742b4e673072066f'
      AvailabilityZone: us-east-1c
      KeyName: KafkaQaKey
      SubnetId: subnet-0f973744a50c4ae86

Resources:
  #Elastic IP that attaches the instance to the Internet
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref MyInstance
  #Root profile that gives permissions, see RootRole
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref RootRole
  #Security Role that describes the service
  RootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  #Defines the permissions
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: "*"
          Resource: "*"
      Roles:
      - !Ref RootRole
  #The actual instance to be created
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref RootInstanceProfile
      KeyName: !FindInMap ['EC2Details', !Ref Environment, 'KeyName']
      SubnetId: !FindInMap ['EC2Details', !Ref Environment, 'SubnetId']
      SecurityGroupIds:
      - !Ref 'InstanceSecurityGroup'
      InstanceType: !FindInMap ['EC2Details', 'CommonDetails', 'InstanceType']
      AvailabilityZone: !FindInMap ['EC2Details', !Ref Environment, 'AvailabilityZone']
      ImageId: !FindInMap ['EC2Details', !Ref Environment, 'AMI']
      #Installs Kafka via user data and an ansible playbook
      UserData: 
        Fn::Base64:
          !Sub |
            #!/bin/bash -ex
            sudo -i
            cd ..
            mkdir userData
            cd userData
            amazon-linux-extras install ansible2 -y
            mkdir EC2Kafka
            aws s3 cp --recursive s3://${SourceBucketName}/ EC2Kafka
            cd EC2Kafka/Ansible
            pwd
            ansible-playbook install_kafka.yml
            systemctl status confluent*
      Tags:
        -
          Key: Name
          Value: !Join ['-', [!Ref AWS::Region, Instance, 'kafka']]
  #Security group that is attached to the instance
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host
        VpcId: !Ref VPC
        SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
        Tags:
        -
          Key: Name
          Value: !Join ['-', [SecurityGroup, !Ref AWS::Region, !Ref Environment]]
        - Key: Version
          Value: 0.1