---
- name: ansible_vault_playbook
- hosts: dev_ec2_host
#need to find a way to specify which host we want based off of environment
- Tasks:
  - name: Create vault user group
    group:
      name: "{{ vault_group }}"
    become: true

  - name: Creating vault user
    user:
      name: "{{ vault_user }}"
      group: "{{ vault_group }}"
      system: yes
      shell: "/sbin/nologin"
      comment: "vault nologin user"
      createhome: "no"
      state: present 
    
  - name: Install prerequisitets
    package:
      name: "{{ item }}"
      update_cache: yes
    with_items: "{{ vault_install_prerequisites }}"
    become: yes

  - name: Download binary
    get_url:
      url: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
      dest: /tmp/vault_{{vault_version}}_linux_amd64.zip
      owner: "{{ vault_user }}"
      group: "{{ vault_group }}"
      mode: 0755

  - name: "Set vault binary capabilities"
    capabilities: 
      path: /usr/local/bin/vault
      capability: cap_pic_lock+ep
      state: present

  # [Unit]
  # Description=Tool for managing secrets
  # Documentation=https://vaultproject.io/docs/
  # After=network.target
  # ConditionFileNotEmpty=/etc/vault.hcl

  # [Service]
  # User=vault
  # Group=vault
  # ExecStart=/usr/local/bin/vault server -config=/etc/vault.hcl
  # ExecReload=/usr/local/bin/kill --signal HUP $MAINPID
  # CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
  # Capabilities=CAP_IPC_LOCK+ep
  # SecureBits=keep-caps
  # NoNewPrivileges=yes
  # KillSignal=SIGINT

  # [Install]
  # WantedBy=multi-user.target

  - name: Copy systemd init file
    template:
      src: init.service.j2
      dest: /etc/systemd/system/vault.service
      owner: root
      group: root
    notify: systemd_reload

  - name: config file
    template:
      src: vault.hcl.j2
      dest: "{{ vault_config_path }}"
      owner: "{{ vault_user }}"
      group: "{{ vault_group }}"
      
  - name: vault service
    service:
      name: vault
      state: started
      enabled: yes