
# File: site.yml - Example Vault server playbook (Filesystem storage)
- name: Install Vault Vagrant Development Server
  hosts: all
  any_errors_fatal: false
  become: true
  become_user: ec2-user
  roles:
    - {role: brianshumate.vault, vault_backend: file}