
# File: site.yml - Example Vault server playbook (Filesystem storage)
- name: Install Vault Vagrant Development Server
  hosts: all
  any_errors_fatal: false
  become: true
  become_user: root
  tasks:
    - name: Package variables
      vault_version: 1.5.5
      vault_architecture_map:
        # this first entry seems... redundant (but it's required for reasons)
        amd64: amd64
        x86_64: amd64
        armv7l: arm
        aarch64: arm64
      vault_architecture: "{{ vault_architecture_map[ansible_architecture] }}"
      vault_os: "{{ ansible_system|lower }}"
      vault_pkg: "vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
      # vault_shasums: "vault_{{ vault_version }}_SHA256SUMS"
      vault_zip_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
      vault_checksum_file_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version}}_SHA256SUMS"

    - name: Install method variables
      vault_install_hashi_repo: false
      vault_install_remotely: false
      vault_privileged_install: false

    - name: Paths
      vault_bin_path: /usr/local/bin
      vault_config_path: /etc/vault.d
      vault_plugin_path: /usr/local/lib/vault/plugins
      vault_data_path: /var/vault
      vault_log_path: /var/log/vault
      vault_run_path: /var/run/vault
      vault_home: "/home/{{ vault_user }}"

    - name: System user and group
      vault_manage_user: true
      vault_user: vault
      vault_manage_group: false
      vault_group: bin
      vault_groups: null

    - name: Logging
      vault_enable_log: false
      vault_enable_logrotate: false
      vault_logrotate_freq: 7
      vault_logrotate_template: vault_logrotate.j2
      vault_exec_output: ''
    # roles:
    #   - {role: brianshumate.vault, vault_backend: file}
